---
- name: Task 2 containers
  hosts: all
  become: yes

  tasks:
    - name: Boot docker-compose file 1
      shell: docker-compose -f /vagrant/ansible_playbooks/docker_c_files/task2/docker-compose.yml up -d
      args:
        executable: /bin/bash

    - name: Boot docker-compose file 2
      shell: docker-compose -f /vagrant/ansible_playbooks/docker_c_files/docker_registry/docker-compose.yml up -d
      args:
        executable: /bin/bash
    
    - name: Boot docker-compose file 3
      shell: docker-compose -f /vagrant/ansible_playbooks/docker_c_files/jenkins/docker-compose.yml up -d
      args:
        executable: /bin/bash
    
    - name: Boot docker-compose file 4
      shell: docker-compose -f /vagrant/ansible_playbooks/docker_c_files/task4/docker-compose.yml up -d
      args:
        executable: /bin/bash
