version: "2"
services:
  master:
    image: jenkins/jenkins:lts
    user: root
    privileged: true
    ports:
    - "9001:8080"
    - "50000:50000"

    volumes:
    - /home/${myname}/jenkins_compose/jenkins_configuration:/var/jenkins_home
    - /var/run/docker.sock:/var/run/docker.sock



